name: Lint
on: [ push, pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
# Since we are using custom script for running linter
# We can't use golangci-lint-action, that run automatically.
#      - uses: golangci/golangci-lint-action@v3
#        with:
#          version: v1.50.0
      - name: Install golang lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
      - name: Run linter
        run: make lint
